import axios from "axios";
import styles from "../../styles/newsDetails.module.css"
import Head from 'next/head'
import {MainLink} from "../../components/baseUrl/BaseUrl";
import Layout from "../../components/Adviser/Layout";
import * as shamsi from 'shamsi-date-converter';



export default function Details({newDetails}){
    return(
        <div className={styles.container}>
            <Head>
                <title>جزئیات محصول</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <section className={styles.main}>
                    <section className={styles.details}>
                        <div className={styles.image}>
                            <img className={styles.big_img} src={newDetails.title_image} alt="photo" />
                        </div>
                        <div className={styles.descreption}>
                            <h1>{newDetails.title}</h1>
                            <hr />
                            <div className={styles.descreption_text}>
                                <div style={{fontSize: '14px' , textAlign: 'justify'}} className="product-des" dangerouslySetInnerHTML={{ __html: newDetails.body }}></div>
                                <p style={{textAlign: 'left' , color: '#999999' , marginTop: '20px' , fontSize: '12px'}}>
                                    {shamsi.gregorianToJalali(newDetails.created_at.split("-")).join('-')} . By {newDetails.author.first_name} {newDetails.author.last_name}
                                </p>
                            </div>
                        </div>
                    </section>
                </section>
            </Layout>
        </div>
    )
}

export async function getServerSideProps(context){
    const {Details} = context.query;
    const newDetails = await axios.get(encodeURI(`${MainLink}/news/rd/${Details}/`))
    const newsResponse = newDetails.data;


    return{
      props:{newDetails: newsResponse}
    }
}
  