// import { FaFileExport } from "react-icons/fa";


export const homeObjectOne = {
    bg:"#142028", 
    imgDisplay:'flex',
    resDisplay:'none',
    resDisplay:'none',
    display3D:"none",
    videoDisplay:'none',
    // video:"videos/watch02.mp4",
    id :'home',
    lightBg: true,
    lightText:false,
    lightTextDesc: false,
    topLine: 'CEO Programming Service',
    headLine:'پلتفرم های اختصاصی تحت وب',
    description: ' برنامه نویسی پلتفرم های یکپارچه روی فریم ورک  شماره یک جهان   React  برای تمام کسب و کارها بصورت 100% اختصاصی و با کدنویسی با زبان های جاوا اسکریپت و پایتون با امکان دسترسی به اینترنت اشیا , بلاک چین و هوش مصنوعی با قابلیت بارگذاری در گوگل پلی , اپل استور و بازار های داخلی.    ',
    btnDisplay: true,
    buttonLable: 'اطلاعات بیشتر و ثبت سفارش',
    buttonLink:"./webservice/software",
    imgStart: true,
    img: './images/s23.webp',
    alt:'مدیریت آنلاین',
    dark: true,
    primary: true,
    darkText: false
};


export const homeObjectTwo = {
    bg:"#142028",
    id :'services',
    resDisplay:'none',
    display3D:"none",
    imgDisplay:'flex',
    videoDisplay:'none',
    // video:"videos/hotel.mp4",
    lightBg: false,
    lightText:false,
    lightTextDesc: true,
    topLine: 'Digital Marketing',
    headLine:'دیجیتال مارکتینگ - فروش و معرفی',
    description: 'در میان میلیون ها اولین باشید , ارائه خدمات تخصصی برنامه نویسی در بستر وب , خدمات تخصصی سئو برای خزنده های گوگل و شبکه های مجازی, اجرا انواع ایده های نوین استارت اپی و  تبلیغاتی مانند فروشگاه های سه بعدی , تست آنلاین با هوش مصنوعی, خدمات  Ar  Vr, ',
    buttonLable: ' اطلاعات بیشتر و ثبت سفارش',
    imgStart:true,
    buttonLink: "/webservice/website",
    img:'./images/digitalmaketing.gif',
    alt:'مدیریت آنلاین',
    dark:true,
    primary:true,
    darkText:false,
    
};


export const homeObjectThree = {
    id :'iot',
    bg:"#142028",
    resDisplay:'none',
    display3D:"none",
    imgDisplay:'flex',
    videoDisplay:'none',
    // video:"videos/5.mp4",
    lightBg: false,
    lightText:false,
    lightTextDesc: false,
    topLine: 'Internet of things',
    headLine:'اینترنت اشیا',
    description: ' برنامه نویسی پلتفرم های رباتیک برای اتوماسیون های صنعتی , بازو های رباتیک و ربات های چند منظوره با امکان دسترسی به پردازشگر های هوش مصنوعی. ',
    description: ' با اینترنت اشیا میتوانید از سراسر جهان تمام سیستم های کنترلی خود را مدیریت کنید , برنامه دهی و کنترل تمام سیستم های الکترونیکی , مانیتورینگ سنسور ها و مشاهده آنلاین جزئیات کسب و کار, امکان کنترل سیستم های رباتیک  , تنها بخشی از کاربردهای اینترنت اشیا در جهان است.',
    buttonLable: ' اطلاعات بیشتر و ثبت سفارش',
    buttonLink:"./webservice/iot",
    imgStart:true,
    img:'./images/s25.png',
    alt:'اینترنت اشیا',
    dark:true,
    primary:true,
    darkText:false,
    
};

export const homeObjectFour = {
    id :'ai',
    bg:"#000",
    resDisplay:'none',
    videoDisplay:'none',
    imgDisplay:'flex',
    // video:"videos/earth2.mp4",
    lightBg: false,
    lightText:false,
    lightTextDesc: false,
    headLine:'راهکارهای هوش مصنوعی',
    topLine: 'Artificial Intelligence',
    description: ' هوش مصنوعی  نسبت به هر کسب  کار ,  کارکرد متفاوتی دارد , ترکیب هوش مصنوعی با پلتفرم های مدیریت آنلاین  باعث دقت بیشتر , هزینه کمتر  و راندمان بیشتر در کسب و کار می شود.  ',
    buttonLable: ' اطلاعات بیشتر و ثبت سفارش',
    buttonLink:"/webservice/machinelearning",
    img: './images/ai05.gif',
    imgStart:true,
    alt: 'مدیریت آنلاین',
    dark:true,
    primary:true,
    darkText:false,
    display3D:"none",
};


export const homeObjectFive = {
    id :'auto',
    bg:"#000",
    resDisplay:'none',
    display3D:"flex",
    imgDisplay:'none',
    videoDisplay:'none',
    // video:"videos/fin.mp4",
    lightBg: true,
    lightText:false,
    lightTextDesc: false,
    topLine: 'Robotic Automation',
    headLine:'اتوماسیون های خود ران و کنترلی',
    description: '  طراحی و اجرا سیستم منعطف رباتیک برای کسب و کارهای پرورشی و صنعتی با ویژگی های چون همکاری تیمی , خود ران , برنامه دهی آسان , مقیاس پذیری , نقشه برداری از محیط و... ',
    buttonLable: '  اطلاعات بیشتر و ثبت سفارش',
    buttonLink:"./webservice/roboticplatform",
    imgStart: true,
    // img: './images/roboarm.png',
    alt:'رباتیک',
    dark: true,
    primary: true,
    darkText: false,
    path:"/images/robot",
    fname:"m{index}.jpg"
};

export const homeObjectsix = {
    id :'crypto',
    bg:"#142028",
    resDisplay:'none',
    display3D:"none",
    imgDisplay:'flex',
    videoDisplay:'none',
    // video:"videos/fin.mp4",
    lightBg: true,
    lightText:false,
    lightTextDesc: false,
    topLine: 'cryptocurrency',
    headLine:'رمز ارز های دیجیتال',
    description: '    رمز ارزهای دیجیتال راهی مطمئن , سریع و ارزان  برای انتقال وجه است از این رو مجموعه مدیریت آنلاین نیز آماده ارائه خدمات بلاک چینی و توسع بلاک چین و بسترهای آموزشی است  ',
    buttonLable: ' اطلاعات بیشتر و ثبت سفارش',
    buttonLink: "/crypto/exchange",
    // buttonLink: "/login",
    imgStart: true,
    img: './images/s30.png',
    alt:'کریپتو',
    dark: true,
    primary: true,
    darkText: false,
    // path:"/images/robot",
    // fname:"m{index}.jpg"
};