import { FaFileExport } from "react-icons/fa";


export const homeObjectOne = {
    bg:"#142028", 
    imgDisplay:'flex',
    resDisplay:'none',
    resDisplay:'none',
    display3D:"none",
    videoDisplay:'none',
    // video:"videos/watch02.mp4",
    id :'home',
    lightBg: true,
    lightText:false,
    lightTextDesc: false,
    topLine: 'خدمات تخصصی برنامه نویسی',
    headLine:'برای تمام پلتفرم ها',
    description: ' برنامه نویسی پلتفرم های یکپارچه ساز برای استارت اپ ها , مجموعه های صنعتی , بازرگانی و مدیریتی بصورت 100% اختصاصی با امکان دسترسی به اینترنت اشیا , بلاک چین و هوش مصنوعی  .  ',
    btnDisplay: true,
    buttonLable: 'اطلاعات بیشتر',
    buttonLink:"./webservice/software",
    imgStart: false,
    img: './images/rent.gif',
    alt:'مدیریت آنلاین',
    dark: true,
    primary: true,
    darkText: false
};


export const homeObjectTwo = {
    bg:"#f4f4f4",
    id :'services',
    resDisplay:'none',
    display3D:"none",
    imgDisplay:'flex',
    videoDisplay:'none',
    // video:"videos/hotel.mp4",
    lightBg: false,
    lightText:false,
    lightTextDesc: false,
    topLine: 'Digital Marketing',
    headLine:'دیجیتال مارکتینگ',
    description: 'در میان میلیون ها اولین باشید , ارائه خدمات تخصصی فروش در فضای وب , خدمات تخصصی سئو برای خزنده های گوگل و شبکه های مجازی, اجرا انواع ایده های نوین تبلیغاتی مانند فروشگاه های سه بعدی , تست آنلاین محصولات , انواع مدل شاپ ها و میلیون شاپ ها و همچنین درگاه های بین المللی رمز ارز در مجموعه مدیریت آنلاین انجام می گیرد. ',
    buttonLable: ' مشاهده فروشگاه های تحت وب',
    imgStart:true,
    buttonLink: "/webservice/website",
    img:'./images/digitalmaketing.gif',
    alt:'مدیریت آنلاین',
    dark:true,
    primary:true,
    darkText:true,
    
};


export const homeObjectThree = {
    id :'iot',
    bg:"#F2F2F2",
    resDisplay:'none',
    display3D:"none",
    imgDisplay:'flex',
    videoDisplay:'none',
    // video:"videos/5.mp4",
    lightBg: false,
    lightText:false,
    lightTextDesc: false,
    topLine: 'Internet of things',
    headLine:'اینترنت اشیا',
    description: ' برنامه نویسی پلتفرم های رباتیک برای اتوماسیون های صنعتی , بازو های رباتیک و ربات های چند منظوره با امکان دسترسی به پردازشگر های هوش مصنوعی. ',
    description: ' با اینترنت اشیا میتوانید از سراسر جهان تمام سیستم های کنترلی خود را مدیریت کنید , برنامه دهی و کنترل تمام سیستم های الکترونیکی , مانیتورینگ سنسور ها و مشاهده آنلاین جزئیات کسب و کار, امکان کنترل سیستم های رباتیک  , تنها بخشی از کاربردهای اینترنت اشیا در جهان است.',
    buttonLable: 'اطلاعات بیشتر',
    buttonLink:"./iot/iotplatform",
    imgStart:false,
    img:'./images/smartiot.gif',
    alt:'online ceo',
    dark:true,
    primary:true,
    darkText:true,
    
};

export const homeObjectFour = {
    id :'ai',
    bg:"#000",
    resDisplay:'none',
    videoDisplay:'none',
    imgDisplay:'flex',
    // video:"videos/earth2.mp4",
    lightBg: false,
    lightText:false,
    lightTextDesc: false,
    headLine:'راهکارهای هوش مصنوعی',
    topLine: 'Artificial Intelligence',
    description: ' هوش مصنوعی اکنون در تمام زمینه ها قابل استفاده است که نسبت به هر کسب  کار ,  کارکرد متفاوتی دارد , ترکیب هوش مصنوعی با اینترنت اشیا سبب ایجاد بسترهای مدیریت آنلاین با قابلیت فعالیت خودکار شده اند.دقت بیشتر , هزینه کمتر  و راندمان بالاتر از نتایج استفاده از هوش مصنوعی در کسب و کار است.  ',
    buttonLable: 'ورود به دنیای هوش مصنوعی',
    img: './images/ai05.gif',
    alt: '1234',
    dark:true,
    primary:true,
    darkText:false,
    display3D:"none",
};


export const homeObjectFive = {
    id :'auto',
    bg:"#000",
    resDisplay:'none',
    display3D:"flex",
    imgDisplay:'none',
    videoDisplay:'none',
    // video:"videos/fin.mp4",
    lightBg: true,
    lightText:false,
    lightTextDesc: false,
    topLine: 'Robotic Automation',
    headLine:'اتوماسیون های خود ران و کنترلی',
    description: '  طراحی و اجرا سیستم منعطف رباتیک برای کسب و کارهای پرورشی و صنعتی با ویژگی های چون team work automation, self drive transport,customise & scaleable ',
    buttonLable: 'ورود به اتوماسیون ها',
    buttonLink:"./robotic/roboticplatform",
    imgStart: false,
    // img: './images/roboarm.png',
    alt:'vaccine',
    dark: true,
    primary: true,
    darkText: false,
    path:"/images/robot",
    fname:"m{index}.jpg"
};

export const homeObjectsix = {
    id :'crypto',
    bg:"#FFFDFD",
    resDisplay:'none',
    display3D:"none",
    imgDisplay:'flex',
    videoDisplay:'none',
    // video:"videos/fin.mp4",
    lightBg: true,
    lightText:false,
    lightTextDesc: false,
    topLine: 'cryptocurrency',
    headLine:'رمز ارز های دیجیتال',
    description: '   بر کسی پوشیده نیست رمز ارزهای دیجیتال راهی مطمئن , سریع و ارزان برای کسب و کارهای تحت وب است از این رو مجموعه مدیرآنلاین نیز آماده ارائه خدمات بلاک چینی از قبیل طراحی و اجرا صرافی های ارز دیجیتال , فروش کالا و خدمات با رمز ارز و بسترهای آموزشی است  ',
    buttonLable: 'ورود به دنیای رمز ارز',
    buttonLink: "/crypto/exchange",
    imgStart: true,
    img: './images/crypto2.gif',
    alt:'vaccine',
    dark: true,
    primary: true,
    darkText: true,
    // path:"/images/robot",
    // fname:"m{index}.jpg"
};